### PR TITLE
created maxExtent, return to original extent if outside

### PR DESCRIPTION
**Pull request by cmartin616**

### CODE REVIEW

**Comment by andywalz** [comment]
need to suppress alert and fix solar layer disappearing
image

**Comment by cmartin616** [comment]
I added extent error checking to geolocator and navbar 'find me'.  It alerts, waits 3 seconds and re-centers on the original extent.  Do we want the user to close out this alert or kill it programatically after the map move??

**Comment by andywalz** [comment]
limitExtent is now presenting with some strange projections issue (only on initial load...panning/zooming fixes it):
capture 20

**Comment by cmartin616** [comment]
I'm working on this.  For some reason, the map loading fires on('change-extent') and causes the skewing.  Removing the map.setExtent fixes it but then it defeats the purpose.  I'm researching it with Esri internally.

**Comment by andywalz** [comment]
Are you using the alert function I added? I think ok for it to timeout but I had the timeout commented out for testing in some branches.

**Comment by cmartin616** [comment]
Current method for geolocate and find me is to go to the location (can't really prevent the functionality or people will be confused why), it displays an alert (using your function), waits 3 seconds (so the user isn't confused) and re-centers on the original location.

The alert persists at this point, as I feel it should.  I'm curious if you think it should disappear after X seconds once re-centered or force the user to click the X to dismiss?

**Comment by andywalz** [comment]
I like disappear after 3.5 seconds but Paul says just let it persist and force click. There is no voice of the people!

**Comment by cmartin616** [comment]
This appears to now be working on my machine.  Can you check it?  The xmax was set too low so the extent change and move was firing on load.  We may need to buffer xmin, ymin and ymax as well but I haven't seen it cause issues yet.

**Comment by andywalz** [comment]
Still having alignment issues and now can't zoom at all.

**Comment by cmartin616** [comment]
I'm discontinuing this.

**Pull request closed without merging**
