### PR TITLE
Results drawer rewrite

### PR DESCRIPTION
**Pull request by cmartin616**
Wait on this one until after SolarCalculator.  A lot of cross over and I'm sure I need to fix conflicts.

This one re-writes the results drawer.  It contains new content but a lot of it is placeholders for things generated by the SolarCalculator.  It also includes the nearby solar installations functionality.

### CODE REVIEW

**Comment by andywalz** [comment]
Nice work on nearby solar...should we leave solar layer displayed? (otherwise need different icon for sure) how hard to allow basemap switching, solar toggling?

**Comment by cmartin616** [comment]
I added all of the above, I believe.  And fixed all the merge issues.  Please test this and pull when you approve.

**Comment by cmartin616** [comment]
Okay, this is ready to pull.

*note* - report is jacked.  I must have messed something up in a conflict resolution so I'll rebuild it once this is accepted.

**Comment by andywalz** [comment]
The local installer link is wrong but I can fix that later...also I do think we should get those buttons out of their own column (see overlap issue) but we can deal with that when we do some more responsiveness stuff. Otherwise looks great! 

capture 4

**Comment by cmartin616** [comment]
You are right there is an overlap that we will need to fix during
responsive changes (as planned).  However, keeping it in its own column is
exactly how you should do the responsive design.  I just have everything in
the app set for medium display and I need to add classes for all smaller
displays once the full layout is done.   For example,  that might be
col-md-1 but it might also be col-sm-3 when we do final design.

**Comment by andywalz** [comment]
I fixed local installers url to pull from config.js in dev

**Pull request merged**
