### PR TITLE
Solar calculator

### PR DESCRIPTION
**Pull request by cmartin616**
Initial solar calculator implementation minus styling.  Contains all of ReportTry 2 as well (report initial layout)

### CODE REVIEW

**Comment by andywalz** [comment]
In both Chrome and Firefox I lose ability to scroll after editing default values. Also I think styling will be important here. Instead of losing the report and the form slides in from top maybe everything greys out except the calculator where by editable values appear as form fields with save/restore/cancel buttons until one is clicked.

capture 21

capture 22

**Comment by cmartin616** [comment]
I fixed the scroll issue.  For whatever reason, Bootstrap instantiates a modal with a class that has overflow-y: auto.  Destroying the modal (when the edit modal appears) and reinstantating the modal (when you dismiss the edit modal) does not apply the class with the overflow-y:auto.  I added it manually to the CSS to force the persistence.

**Comment by andywalz** [comment]
I'm not seeing commits on this branch since 10/23. Did your fix maybe not git pushed?

**Comment by cmartin616** [comment]
Can you check again?  I see it through the browser.

image

**Comment by andywalz** [comment]
I'm still having issue with the report after editing the calculator values (e.g. maps now disappear.) however the calculator is working wonderfully and since that is what this branch is about I'm just going to merge it in. We'll deal with styling and report issues later in the report story.

**Pull request merged**
